"""link_documents_to_users

Revision ID: 6005cfafd15f
Revises: 2f395692b7ca
Create Date: 2026-01-17 19:25:24.113610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6005cfafd15f'
down_revision: Union[str, None] = '2f395692b7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'owner_id')
    # ### end Alembic commands ###
